config/routes.rb
Rails.application.routes.draw do

  
  root 'application#root'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  
  get 'users/:username/' => 'users#showuser'
  
  resources :users
  resources :groups

end

app/models/group.rb
class Group < ActiveRecord::Base
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def root
    #
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def create
    phash = {}
    phash[:groupname] = params[:group][:groupname]
    phash[:permissions] = params[:group][:permissions]
    @group = Group.new(phash)
 
    respond_to do |format|
      if @group.save
        format.html { redirect_to(@group, notice: 'Group was successfully created.') }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    @groups = Group.all
  end

  def edit
  end

  def new
    @group = Group.new
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.first(username: params[:user][:username])
    if @user.nil?
    
    phash = {}
    phash[:email] = params[:user][:email]
    phash[:username] = params[:user][:username]
    phash[:firstname] = params[:user][:firstname]
    phash[:middlename] = params[:user][:middlename]
    phash[:lastname] = params[:user][:lastname]
    phash[:salt] = 'salt'
    if( params[:hashed] == 'true' )
      phash[:passhash] = Digest::MD5.hexdigest(params[:user][:passhash]+Digest::MD5.hexdigest(phash[:salt]))
    else
      phash[:passhash] = Digest::MD5.hexdigest(Digest::MD5.hexdigest(params[:password])+Digest::MD5.hexdigest(phash[:salt]))
    end
    # generate salt
    phash[:group] = Group.find(1)
    @user = User.new(phash)
 
    respond_to do |format|
      if @user.save
        # Tell the UserMailer to send a welcome email after save
        UserMailer.welcome_email(@user, request.domain).deliver
 
        format.html { redirect_to(@user, notice: 'User was successfully created.') }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
    
    else
        format.html { redirect_to(new_user_path, notice: 'User with that name already exists.') }
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def showuser
    @user = User.first(params[username: params[:username]])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def index
    @users = User.all
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Dimiourgia"
    if page_title.empty?
      base_title
    else
      "#{base_title} - #{page_title}"
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/root.html.erb
<h1>Welcome to Dimiourgia!</h1>

<p><%= link_to 'Login', '/login' %> | <%= link_to 'Resister', new_user_path %></p>

app/views/groups/create.html.erb
<h1>Groups#create</h1>
<p>Find me in app/views/groups/create.html.erb</p>

app/views/groups/destroy.html.erb
<h1>Groups#destroy</h1>
<p>Find me in app/views/groups/destroy.html.erb</p>

app/views/groups/index.html.erb
<h1>Group Index</h1>

<table>
  <thead>
    <tr>
      <th>Groupname</th>
      <th>Permissions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.groupname %></td>
        <td><%= group.permissions %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/groups/new.html.erb
<h1>Create Group - Dimiourgia</h1>

<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :Groupname %><br>
    <%= f.text_field :groupname %>
  </div>
  <div class="field">
    <%= f.label :Permissions %><br>
    <%= f.number_field :permissions %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Home', root_path %> | <%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<h1><%= @group.groupname %></h1>
<ol>
    <li><strong>Permissions: </strong><%= @group.permissions %></li>
</ol>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Dimiourgia</a>
    by <a href="#">Alpha</a>
    for <a href="#">Ophiuchus</a> 
    by <a href="#">Altair</a>
  </small>
  <nav>
    <ul>
      <li><a href="#">About</a></li>
      <li><a href="#">Contact</a></li>
      <li><a href="#">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render 'layouts/footer' %>
    </div>

</body>
</html>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/index.html.erb
<h1>User Index</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.lastname %>, <%= user.firstname %> <%= user.middlename %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<h1>Sign up - Dimiourgia</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :Username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :FirstName %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :MiddleName %><br>
    <%= f.text_field :middlename %>
  </div>
  <div class="field">
    <%= f.label :LastName %><br>
    <%= f.text_field :lastname %>
  </div>
  <div class="field">
    <%= f.label :Password %><br>
    <%= password_field_tag(:password) %>
  </div>
  <div class="field">
    <%= f.label :ConfirmPassword %><br>
    <%= password_field_tag(:cpassword) %>
  </div>
  <div class="field">
    <%= f.hidden_field :passhash %>
  </div>
  <div class="field">
    <%= hidden_field_tag(:hashed, 'false') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Home', root_path %> | <%= link_to 'Login', login_path %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<ol>
    <li><strong>Email: </strong><%= @user.email %></li>
    <li><strong>First Name: </strong><%= @user.firstname %></li>
    <li><strong>Middle Name: </strong><%= @user.middlename %></li>
    <li><strong>Last Name: </strong><%= @user.lastname %></li>
</ol>

app/views/users/showuser.html.erb
<h1><%= @user.username %></h1>
<ol>
    <li><strong>Email: </strong><%= @user.email %></li>
    <li><strong>First Name: </strong><%= @user.firstname %></li>
    <li><strong>Middle Name: </strong><%= @user.middlename %></li>
    <li><strong>Last Name: </strong><%= @user.lastname %></li>
</ol>